### ISSUE TITLE
How can I merge 2 allure reports? 

### ISSUE THREAD

**Issue by alexnot95** [eroshenkoam/xcresults#25]
Currently, I have localization tests with fastlane snapshot, I have 6 the same tests which runs on 16 different locales, after the run I have 16 different .xcresult files, If I will put them in one with this func:
```
def generateAllureReport(xcresultPath: String)
  pathToAllureFile = File.join('~/Library/Caches', "xcresults")
  output_dir = File.absolute_path("./test_output/allure")
  if File.file?(pathToAllureFile) == false
   sh("wget https://github.com/eroshenkoam/xcresults/releases/latest/download/xcresults -O #{pathToAllureFile}")
   sh("chmod +x #{pathToAllureFile}")
  end
  sh("#{pathToAllureFile} export #{xcresultPath} #{output_dir}")
end
```
 and then link allure-report to Jenkins job, the report shows 0 tests, how can I merge several allure reports?
With 1 locale and 1 xcresult everything works fine, also on StackOverflow, I saw this solution but it seems doesn't work
![Screenshot 2020-12-03 at 12 50 10](https://user-images.githubusercontent.com/37154209/101000190-34944280-3566-11eb-956f-4adc28bf863b.png)

P.S. also in console log I see this error: 
```
12:33:18  java.lang.NullPointerException[0m
12:33:18  at io.eroshenkoam.xcresults.export.ExportCommand.runUnsafe(ExportCommand.java:101)[0m
12:33:18  at io.eroshenkoam.xcresults.export.ExportCommand.run(ExportCommand.java:86)[0m
12:33:18  at picocli.CommandLine.executeUserObject(CommandLine.java:1769)[0m
12:33:18  at picocli.CommandLine.access$900(CommandLine.java:145)[0m
12:33:18  at picocli.CommandLine$RunLast.handle(CommandLine.java:2141)[0m
12:33:18  at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)[0m
12:33:18  at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1975)[0m
12:33:18  at picocli.CommandLine.execute(CommandLine.java:1904)[0m
12:33:18  at io.eroshenkoam.xcresults.XCResults.main(XCResults.java:13)[0m
```

**Comment by alexnot95** [comment]
@eroshenkoam 🙏

**Comment by CyberOwl** [comment]
I think you should try built-in xcode toolset before generate allure report

`xcrun xcresulttool merge`

**Comment by alexnot95** [comment]
Ok, figured out why I saw this error in console log, it was just a wrong path. 
I'm able to generate 2 allure reports into the one file but jenkins plugin - allure-report can't merge 2 allure files :( In jenkins job I see linked allure file only for the last locale :(

@CyberOwl I tried already with fastlane/test-center plugin there is - collate_xcresults method, under the hood it uses xcrun xcresulttool merge command - 
```
if xcresult_bundlepaths.size > 1
          command = [
            'xcrun',
            'xcresulttool',
            'merge',
            xcresult_bundlepaths,
            '--output-path',
            tmp_collated_xcresult_bundlepath
          ].flatten
          commands_run = sh(*command)

```

But it works incorrectly, I have 16 xcresult files for each locale, these files contains the same tests because I'm using fastlane snapshot to run the same tests on different locales, and after merging all xcresults into the 1, it shows only result for the last locale :( and if 5th locale have 2 failed tests and the last locale xcresult file have all passed tests, I will see all tests are passed... Maybe you have an idea of how I can workaround this issue? 
I know that I can create 16 separate classes for each locale in the project and everything will be fine, but it's so stupid... :(
