### ISSUE TITLE
Assertion message not showing in Allure report for Xcode 14

### ISSUE THREAD

**Issue by nGervasyuk** [eroshenkoam/xcresults#40]
STR

1. Create and run simple failure test, example `XCTAssertFalse(true, "assertion message")`
2. Generate allure report using `xcresults` CLT
3. Pay attention for error message in Allure report and for statusMessage field in `.json` result file

ER: statusMessage exists and contains assertion message
AR: statusMessage not exists

Started to reproduced after update to Xcode 14 for `XCTAssertFalse` and sometimes for `XCTAssertTrue` functions

**Comment by cheshi-mantu** [comment]
@nGervasyuk hello there
added to backlog
