### ISSUE TITLE
Bad CPU type in executable

### ISSUE THREAD

**Issue by Azer0thian** [eroshenkoam/xcresults#47]
Hello!

I can't execute with script for generate allure results on Mac mini with Apple Silicon M1. 

Take error:
`zsh: bad CPU type in executable: ./xcresults`

Can you help me?

Продублирую на русском:

Привет!

При попытке запустить данный скрипт на Mac Mini с M1 процессором, вышеуказанную ошибку.

Сможете помочь? Там выпустить версию с поддержкой Apple Silicon, или как-то помочь запустить?

**Comment by FloxD** [comment]
I ran into the same issue and solved it by enabling Rosetta 2 by executing `softwareupdate --install-rosetta` in the terminal
